"""202512251444

Revision ID: 23f5ce1346ba
Revises: f3d893ccb866
Create Date: 2025-12-25 14:42:51.986417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f5ce1346ba'
down_revision: Union[str, None] = 'f3d893ccb866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='姓名'))
    # ### end Alembic commands ###
