"""202512251740

Revision ID: 5531240c344d
Revises: 23f5ce1346ba
Create Date: 2025-12-25 17:47:06.575569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5531240c344d'
down_revision: Union[str, None] = '23f5ce1346ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builtin_tool_configs', sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('builtin_tool_configs', sa.Column('requires_config', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tool_configs', sa.Column('icon', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_configs', 'icon')
    op.drop_column('builtin_tool_configs', 'requires_config')
    op.drop_column('builtin_tool_configs', 'is_enabled')
    # ### end Alembic commands ###
