"""202512191805

Revision ID: f96a53af914c
Revises: 87a6537b4074
Create Date: 2025-12-19 18:05:14.964454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96a53af914c'
down_revision: Union[str, None] = '87a6537b4074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_config', sa.Column('reflection_model_id', sa.String(), nullable=True, comment='反思模型ID'))
    op.add_column('data_config', sa.Column('memory_verify', sa.Boolean(), nullable=True, comment='记忆验证'))
    op.add_column('data_config', sa.Column('quality_assessment', sa.Boolean(), nullable=True, comment='质量评估'))
    op.add_column('end_users', sa.Column('reflection_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'reflection_time')
    op.drop_column('data_config', 'quality_assessment')
    op.drop_column('data_config', 'memory_verify')
    op.drop_column('data_config', 'reflection_model_id')
    # ### end Alembic commands ###
